--Drops all objects created - users, roles, DBs and WHs

use role accountadmin;
drop share global_sales_share;
use role sysadmin;
drop warehouse if exists accounting_wh;
drop warehouse if exists analytics_wh;
drop warehouse if exists etl_wh;
drop warehouse if exists bi_reporting_wh;
drop warehouse if exists finance_wh;
drop warehouse if exists hr_wh;
drop warehouse if exists it_wh;
drop warehouse if exists data_science_wh;
drop warehouse if exists product_wh;
drop warehouse if exists sales_wh;
drop warehouse if exists ops_support_wh;
drop warehouse if exists sandbox_wh;
drop database if exists global_sales;
drop database if exists inventory;
drop database if exists loyalty;
drop database if exists payroll;
drop database if exists salesforce;
drop database if exists common;
drop database if exists stores;
drop database if exists suppliers;
drop database if exists support;
drop database if exists web_logs;
use role securityadmin;
drop role if exists sales_admin;
drop role if exists marketing_admin;
drop role if exists data_science;
drop role if exists finance_admin;
drop role if exists hr_admin;
drop role if exists product_manager;
drop role if exists governance_admin;
drop role if exists sales_analyst;
drop role if exists marketing_analyst;
drop role if exists finance_analyst;
drop role if exists hr_analyst;
drop role if exists master_data_access;
drop user if exists Dan;
drop user if exists Adam;
drop user if exists Sachin;
drop user if exists Anand;
drop user if exists Aaron;
drop user if exists Alex;
drop user if exists Brett;
drop user if exists Brian;
drop user if exists Caroline;
drop user if exists Dinesh;
drop user if exists Diana;
drop user if exists Divya;
drop user if exists Emma;
drop user if exists Grace;
drop user if exists Irina;
drop user if exists Jack;
drop user if exists Justin;
drop user if exists Zack;
drop user if exists Frank;
drop user if exists Praveen;
drop user if exists David;
drop user if exists Prasanna;
drop user if exists Padmaja;
drop user if exists Jenna;